name: Build Repository
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  xStreamMain:
    permissions:
      contents: write
    uses: ./.github/workflows/BuildKodiAddon.yml
    with:
      addon_repo: "plugin.video.xstream"
      addon_branch: "main"
  xShipMain:
    needs: xStreamMain
    permissions:
      contents: write
    uses: ./.github/workflows/BuildKodiAddon.yml
    with:
      addon_repo: "plugin.video.xship"
      addon_branch: "main"
  xStreamNightly:
    needs: xShipMain
    permissions:
      contents: write
    uses: ./.github/workflows/BuildKodiAddon.yml
    with:
      addon_repo: "plugin.video.xstream"
      addon_branch: "nightly"
  xShipNightly:
    needs: xStreamNightly
    permissions:
      contents: write
    uses: ./.github/workflows/BuildKodiAddon.yml
    with:
      addon_repo: "plugin.video.xship"
      addon_branch: "nightly"
